### ISSUE TITLE
LLVM version

### ISSUE THREAD

**Issue by minoki** [smlsharp/homebrew-smlsharp#1]
私のMac（macOS Big Sur）で `brew install smlsharp` を試したところ、依存関係にある `llvm@9` のビルドが失敗しました。

SML# 4.0.0はLLVM 11.1.0に対応したとのことなので、 `llvm@11` を参照するようにformulaを更新すると良いかと思います（私の環境ではそれでビルドできました）。

**Comment by uenoB** [comment]
報告ありがとうございます。`llvm@9`のビルドに失敗するとは思いませんでした。そういう問題を孕んでいるならば`llvm@11`を使いたいと思います。

以前は`depend_on "llvm"`としていたんですが、そうするとLLVMのバージョンが上がったときにSML#が動かなくなる問題があったので（SML#はビルドに使用したLLVMのバージョンに依存します）、もうアップデートされないであろうバージョンのうち最新のもの（`llvm@9`）を使っていました。
